# Generated by Django 2.2.5 on 2022-07-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_post_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
