# Generated by Django 2.2.5 on 2022-07-26 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220726_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducatiodetail',
            name='cert_degree_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usereducatiodetail',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usereducatiodetail',
            name='institution_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usereducatiodetail',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
