# Generated by Django 2.2.5 on 2022-08-27 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220827_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='dateposted',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2022, 8, 27, 9, 48, 5, 506750, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
