# Generated by Django 2.2.5 on 2022-08-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20220830_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='fieldImage',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
